### ISSUE TITLE
Possible fix for mac build in GitHub Actions

### ISSUE THREAD

**Issue by LithyRiolu** [ConcealNetwork/conceal-core#128]
**Is your feature request related to a problem? Please describe.**
Yes, the Mac build on [GitHub Actions](https://github.com/ConcealNetwork/conceal-core/actions)

**Describe the solution you'd like**
I think the fix would be placed here; `conceal-core/CMakeLists.txt#L27`
```cpp
if(APPLE)
  include_directories(SYSTEM /usr/include/malloc)
  enable_language(ASM)
endif()
```
to
```cpp
if(APPLE)
  include_directories(SYSTEM /usr/include/malloc)
  enable_language(ASM)
  set(CMAKE_C_ARCHIVE_CREATE   "<CMAKE_AR> Scr <TARGET> <LINK_FLAGS> <OBJECTS>")
  set(CMAKE_CXX_ARCHIVE_CREATE "<CMAKE_AR> Scr <TARGET> <LINK_FLAGS> <OBJECTS>")
  set(CMAKE_C_ARCHIVE_FINISH   "<CMAKE_RANLIB> -no_warning_for_no_symbols -c <TARGET>")
  set(CMAKE_CXX_ARCHIVE_FINISH "<CMAKE_RANLIB> -no_warning_for_no_symbols -c <TARGET>")
endif()
```

**Additional context**
This is after discovering the mac build fails on GitHub Actions and after reading more into it, I think I found the solution [here](https://github.com/avast/retdec/pull/349)

**Comment by krypt0x** [comment]
A team member will analyse your request soon. Thank you.

**Comment by cryptokatz** [comment]
Thanks. One thing to note is that the macOS build was not failing about two to three releases back. My first instinct is to look at what changes we made that would cause this failure before I make additional changes.

**Comment by krypt0x** [comment]
The macOS workflow is now fixed. Thank you for participating.
