### ISSUE TITLE
Error at block 113910

### ISSUE THREAD

**Issue by Marchay** [ConcealNetwork/conceal-core#17]
Always get this error : -
`17:01:05.840053 INFO CHECKPOINT PASSED FOR HEIGHT 113911 <e0e31bf93583b080f12d56943914125a31b95ab7e2688f983b11dc8105b31f26>
17:01:05.910238 ERROR Coinbase transaction spend too much money: 6.250100, block reward is 6.250099
17:01:05.910794 INFO Block <e0e31bf93583b080f12d56943914125a31b95ab7e2688f983b11dc8105b31f26> has invalid miner transaction` Never synching after that

**Comment by therealmadmax** [comment]
As wee said on discord... Install latest version, delete all block data and resync your wallet.

CLI Wallet

Stop daemon
Delete *.dat and *.bin in ~/.conceal (linux/macOS) or %appdata%/conceal (windows)
Download and unpack fixed blockchain from the release
Download current release
Start daemon
Reset your wallet

GUI Wallet

Close Wallet
Delete *.dat and *.bin in ~/.conceal (linux/macIS) or %appdata%/conceal (windows)
Download and unpack fixed blockchain from the release
Download current release
Start Wallet
Setttings > Rescan Wallet

The releases for Windows, macOS, and Ubuntu are here:

https://github.com/ConcealNetwork/conceal-core/releases

https://github.com/ConcealNetwork/conceal-wallet/releases

**Comment by therealmadmax** [comment]
I am closing this thread. This is not an issue of Conceal software. If you need any extra guidance please align to the official discord.
