### ISSUE TITLE
RPC issue

### ISSUE THREAD

**Issue by Marchay** [ConcealNetwork/conceal-core#18]
I have successfully started the RPC server with following command `./walletd --daemon-address 127.0.0.1 --daemon-port 16000 --bind-address 127.0.0.1 --bind-port 3090 --rpc-user
User --rpc-password Password -w wallet -p password`.
Now when I try use the curl for rpc like this `curl -X POST http://127.0.0.1:3090/json_rpc -u User:Password --digest -d '{"jsonrpc":"2.0","id":"0","method":"getheight"}' -H 'Content-Type: application/json'`, I get Authorization required and in walletd trails this `WARNING [HttpServer] Authorization required 127.0.0.1:60838` thats `60838` keeps changing as I keep trying new curls

**Comment by cryptokatz** [comment]
@Marchay 

Try changing your curl command to this:
curl -d '{"params":{},"jsonrpc":"2.0","id":"test","method":"getBalance"}' http://username:password@localhost:3090/json_rpc

Your example had getheight, which is not a method on walletd. It is available on the daemon or concealwallet. You can see some examples of the commands available through either wallet here: https://github.com/ConcealNetwork/conceal-js (this is for javascript, but the calls are the same). Another thing to remember is that Conceal RPC calls use camelCase, so getheight would actually be getHeight.

Also, you don't need to specify daemon-address and port unless you are using a different or remote node.

If you need faster support, you can catch me on Discord.

**Comment by Marchay** [comment]
Thanks worked
