### ISSUE TITLE
 Issue with cli - print_bc not printing block range

### ISSUE THREAD

**Issue by englishcoder** [ConcealNetwork/conceal-core#282]
Command:
 print_bc         Print blockchain info in a given blocks range, print_bc <begin_height> [<end_height>]

Issue:
When issuing command with a span of blocks it only appears to print the first block
commands tested (current height at time of test was 969384)
print_block 969380 969383 
print_block 969370 969373

**Desktop (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.19044.1526]

**Additional context**
Version Tested: https://github.com/ConcealNetwork/conceal-core/actions/runs/1853819425 (ccx-cli-windows-dev-e43f91a)

**Comment by AxVultis** [comment]
`print_bc` is working as expected but output was no visible by default, it is now fixed in development branch.
It seems you mixed `print_bc` and `print_block` commands.

**Comment by englishcoder** [comment]
Not sure how I mixed those up when writing up the ticket, thanks.

Test Outcome:
Passed

OS:
Microsoft Windows [Version 10.0.19044.1566]

Version Tested:
https://github.com/ConcealNetwork/conceal-core/actions/runs/1941339378 (ccx-cli-windows-dev-b74fee7)

Test Output:
`print_bc 969380 969383
14:31:31.967332 INFO Blockchain:
height 969380, timestamp 1645498044, cumul_dif 404613357727459, cumul_size 18483
id <21f6107e4103ea49f57f3fb1a4389fcfd1656f26cc89f7435860657bce8e70dd>
difficulty 201000000, nonce 536953410, tx_count 9
height 969381, timestamp 1645498608, cumul_dif 404613523727459, cumul_size 100
id
difficulty 166000000, nonce 12747, tx_count 0
height 969382, timestamp 1645498659, cumul_dif 404613670727459, cumul_size 100
id <2c40ac112f0e67e92545062a73aa50e8998108b899b29e7d587d52d16b420309>
difficulty 147000000, nonce 536872323, tx_count 0

print_bc 969370 969373
14:31:53.455152 INFO Blockchain:
height 969370, timestamp 1645496017, cumul_dif 404611568727459, cumul_size 100
id
difficulty 157000000, nonce 87364, tx_count 0
height 969371, timestamp 1645496186, cumul_dif 404611730727459, cumul_size 14578
id <5dbc841d0e69be1f13f649678a0acfc4a7d5d52d3736f1d158b6362ee951811a>
difficulty 162000000, nonce 13345, tx_count 6
height 969372, timestamp 1645496205, cumul_dif 404611890727459, cumul_size 100
id
difficulty 160000000, nonce 268439069, tx_count 0`
