### ISSUE TITLE
Does not appear to compile under Debian Bullseye

### ISSUE THREAD

**Issue by iwiwao** [ConcealNetwork/conceal-core#321]
**Describe the bug**
Link error in PaymentGateService.cpp.o against Boost

**To Reproduce**
compile the code.

`/usr/bin/ld: CMakeFiles/PaymentGateService.dir/PaymentGateService/PaymentGateService.cpp.o: in function `__static_initialization_and_destruction_0(int, int)':
PaymentGateService.cpp:(.text+0x2fba): undefined reference to `boost::system::generic_category()'
/usr/bin/ld: PaymentGateService.cpp:(.text+0x2fc6): undefined reference to `boost::system::generic_category()'
/usr/bin/ld: PaymentGateService.cpp:(.text+0x2fd2): undefined reference to `boost::system::system_category()'
/usr/bin/ld: CMakeFiles/PaymentGateService.dir/PaymentGateService/PaymentGateService.cpp.o: in function `boost::system::error_category::std_category::equivalent(int, std::error_condition const&) const':
`

**Comment by krypt0x** [comment]
The boost library you are using depends on the boost_system library. (Not all of them do.)

Assuming you use gcc, try adding -lboost_system to your compiler command line in order to link against that library.

**Comment by AxVultis** [comment]
Hey @iwiwao 

How are you compiling the code?

I tested on a fresh virtual machine and had no issue.

**Comment by AxVultis** [comment]
Did you installed boost via `apt install libboost-all-dev`?

**Comment by krypt0x** [comment]
Have you sorted it out already? If not, try to add these lines to your cmake file:

`find_package(Boost 1.55.0 REQUIRED COMPONENTS system filesystem)
include_directories(... ${Boost_INCLUDE_DIRS})
link_directories(... ${Boost_LIBRARY_DIRS})
target_link_libraries(... ${Boost_LIBRARIES})`

**Comment by iwiwao** [comment]
Sorry to be a pain, but I wanted to verify I tossed those lines in the correct cmake file - I'm entering them into the CMakeLists.txt file - is that the correct place?  If so, I receive a new and exciting error:

`
CMake Error at CMakeLists.txt:160 (target_link_libraries):
  Cannot specify link libraries for target "..." which is not built by this
  project.
`

I also double-checked and do have the required packages installed.

**Comment by AxVultis** [comment]
If all dependencies are installed properly, (including include path) nothing need to be changed.
It should compile without changes.

Could you try again to build from latest release?

**Comment by krypt0x** [comment]
> Sorry to be a pain, but I wanted to verify I tossed those lines in the correct cmake file - I'm entering them into the CMakeLists.txt file - is that the correct place? If so, I receive a new and exciting error:
> 
> `CMake Error at CMakeLists.txt:160 (target_link_libraries): Cannot specify link libraries for target "..." which is not built by this project.`
> 
> I also double-checked and do have the required packages installed.

remove the 3 dots (`...`)

**Comment by krypt0x** [comment]
> If all dependencies are installed properly, (including include path) nothing need to be changed. It should compile without changes.
> 
> Could you try again to build from latest release?

This is accurate.

**Comment by iwiwao** [comment]
No dice removing the three dots - but since we know this will compile properly on a fresh install of Bullseye, I'll just plan for a fresh install when I have time.  Thank you both for the help.

**Comment by cartoon-face** [comment]
Hello, I have managed to install conceal-core on a fresh install on Debian Bullseye.

Here are the steps I took:
- I got the latest ISO from: https://www.debian.org/releases/bullseye/debian-installer/ downloading `netinst CD image`
- I let it do its full start-up install and reset
- Then I entered super user using `su -` and proceeded to install sudo, and change the user in `visudo`
- I used `apt-get git-all` for git and cloned conceal-core
- Then finally, `apt install cmake libboost-dev libboost-all-dev`
- Proceeded to `make` within `conceal-core/`

I hope this helps.

![image](https://user-images.githubusercontent.com/92698655/224482074-38f3b41f-8661-4cb6-8141-d3ac6fd557e7.png)

**Comment by cartoon-face** [comment]
@iwiwao Did you manage to solve this issue?

**Comment by iwiwao** [comment]
Fresh install is not the issue - this is an upgraded install and probably has leftover cruft around that's causing issues.  Either way, I'm rebuilding the node with a fresh install of Debian or Ubuntu this week.  But to answer your question, no I did not get this working, I just didn't have enough time to mess with it.
